parameters:

services:

  logger:
    alias: monolog.logger
    public: true

  Wienerio\ShopwarePrometheusExporter\Controller\Storefront\MetricsController:
    public: true
    arguments:
      - '@Wienerio\ShopwarePrometheusExporter\Services\MetricsHandler'
      - '@logger'
    calls:
      - setContainer: ['@service_container']

  Wienerio\ShopwarePrometheusExporter\Services\MetricsHandler:
    arguments:
      - !tagged 'sw.prometheus.metric'
      - '@logger'

  Wienerio\ShopwarePrometheusExporter\Services\Metric\OrdersCountTotal:
    arguments:
      - '@Doctrine\DBAL\Connection'
      - '@Shopware\Core\System\SystemConfig\SystemConfigService'
      - '@logger'
    tags: ['sw.prometheus.metric']

  Wienerio\ShopwarePrometheusExporter\Services\Metric\OrdersAmountTotal:
    arguments:
      - '@Doctrine\DBAL\Connection'
      - '@Shopware\Core\System\SystemConfig\SystemConfigService'
      - '@logger'
    tags: ['sw.prometheus.metric']

  Wienerio\ShopwarePrometheusExporter\Services\Metric\CustomersCountTotal:
    arguments:
      - '@Doctrine\DBAL\Connection'
      - '@Shopware\Core\System\SystemConfig\SystemConfigService'
      - '@logger'
    tags: ['sw.prometheus.metric']

  #################################
  # Command
  #################################
  Wienerio\ShopwarePrometheusExporter\Command\TestCommand:
    arguments:
      - !tagged 'sw.prometheus.metric'
    tags: [ { name: console.command, command: "wio:prometheus:metrics:test" } ]