parameters:

services:

  logger:
    alias: monolog.logger
    public: true

  Wienerio\ShopwarePrometheusExporter\Controller\Storefront\MetricsController:
    arguments:
      - '@Shopware\Core\System\SystemConfig\SystemConfigService'
      - !tagged 'sw.prometheus.metric'
      - '@logger'

  Wienerio\ShopwarePrometheusExporter\Services\MetricsCollector:
    arguments:
      - '@Shopware\Core\System\SystemConfig\SystemConfigService'
      - !tagged 'sw.prometheus.metric'
      - '@logger'

  Wienerio\ShopwarePrometheusExporter\Services\Metric\Order:
    arguments:
      - '@logger'
    tags: ['sw.prometheus.metric']

  Wienerio\ShopwarePrometheusExporter\Services\Metric\Customer:
    arguments:
      - '@logger'
    tags: ['sw.prometheus.metric']

  Wienerio\ShopwarePrometheusExporter\Services\Metric\Product:
    arguments:
      - '@logger'
    tags: ['sw.prometheus.metric']
